# Generated by Django 3.2 on 2023-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Customer Enquiries'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
